class StrategyConfig:
    MAX_OPEN_POSITIONS = 1
    ENTRY_AMOUNT_SOL = 7.0
    STOP_LOSS_PCT = -0.05
    TAKE_PROFIT_Target1 = 0.10
    TP_Target1_Ratio = 0.5
    TRAILING_ACTIVATION = 0.05
    TRAILING_DROP = 0.03
    BUY_THRESHOLD = 0.85
    SELL_THRESHOLD = 0.45
